# Generated by Django 4.1.2 on 2022-11-13 20:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='residencia',
            fields=[
                ('num_res', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('fono', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=50)),
            ],
            options={
                'verbose_name': 'Residencia',
                'verbose_name_plural': 'Residencias',
                'ordering': ['num_res'],
            },
        ),
        migrations.CreateModel(
            name='correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField(default=datetime.datetime.today)),
                ('remitente', models.CharField(max_length=50)),
                ('destinatario', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('E', 'Entregado'), ('W', 'En espera'), ('N', 'No entregado')], default='W', max_length=1)),
                ('conserje', models.CharField(max_length=50)),
                ('num_res', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.residencia')),
            ],
            options={
                'verbose_name': 'Correspondencia',
                'verbose_name_plural': 'Correspondencias',
                'ordering': ['fecha_recepcion'],
            },
        ),
    ]
